name: lorcana_score_keeper
description: Application mobile pour compter les points durant une partie de Lorcana
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Local Storage
  hive_ce: 2.6.0
  hive_ce_flutter: 2.1.0
  path_provider: ^2.1.2
  
  # Utilities
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  uuid: ^4.3.3
  
  # UI
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build runners
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_ce_generator: ^1.6.0

  # Testing
  mocktail: ^1.0.3

  # Linting
  flutter_lints: ^3.0.1
  analyzer: ^7.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/player_icons/
